services:
  app:
    image: eibrahim/fluid-calendar:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_EXTRA_CA_CERTS=/app/ca-bundle.pem
    volumes:
      - /home/martijn/Nix/secrets/keys/hadouken.crt:/app/ca-bundle.pem:ro
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=fluid
      - POSTGRES_PASSWORD=fluid
      - POSTGRES_DB=fluid_calendar
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fluid -d fluid_calendar"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_dev_data:
